# Generated by Django 4.1.7 on 2023-03-09 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='providers',
            name='search_returns',
            field=models.IntegerField(default=0, editable=False),
        ),
    ]
